- name: Install Python Deps
  ansible.builtin.yum:
    names:
      - python3-PyMySQL
      - mysql
    state: installed

- name: Load MySQL schema
  community.mysql.mysql_db:
    state: import
    name: all
    target: /app/schema/{{component}}.sql
    login_host: mysql-dev.jahanjo.online
    login_user: root
    login_password: "{{ root_mysql_password }}"